name: starryconsciousness
favicon: null
layout_spectrum: 0.2563033171463758
typography_spectrum: 0.5001779699232429
title: starry consciousness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6385292282793671
  lightness: 0.8023963121231645
  saturation: 0.13031768333166838
  rhythmicContrast: 0.379435645416379
purpose: []
